swiftmailer:
    transport:        gmail
    username:         '%env(MAILER_USER)%'
    password:         '%env(MAILER_PASSWORD)%'
    host:             smtp.gmail.com
    port:             587
    encryption:       tls
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
